image:  docker:19.03.1

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  IMAGE: registry.gitlab.com/instaq-epsi/rust-api
  RELEASE_IMAGE: $IMAGE:latest
  KUBE_CONFIG: $KUBE_CONFIG 
  DEPLOYMENT: rust-api-app
  CONTAINER: rust-api
  NAMESPACE: instaq

services:
  - docker:19.03.1-dind
build:
  stage: build
  script:
    - docker login -u $CI_USER -p $ACCESS_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE
  # tags: 
  #   - instaq

deploy_staging:
  stage: deploy
  image: registry.gitlab.com/instaq-epsi/docker-kubectl:latest
  script:
    - printf "$KUBE_CONFIG" > $HOME/.kube/config
    - cat $HOME/.kube/config
    - kubectl rollout restart deployment/rust-api-app -n instaq
  only:
    - master
  # tags: 
  #   - instaq
