version: "3"
services:
  postgres:
    image: postgres:latest
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data2
volumes:
  postgres: ~